version: '3.7'

services:
  chall:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
  memcached:
    container_name: memcached
    image: memcached:latest
    #command: 'sudo apt update && sudo apt install -y ncat'
    ports:
      - "11211:11211"
